### PR TITLE
Add tikz to mkDoc

### LINKED ISSUE #11: Add tikz to mkdoc
`tikz` is a well recoganized package in `Latex` allowing to provide diagrams, graphs, pictures etc. It would be helpful if `danalib/internal/mkdoc.nix` included `tikz`.

### PR DESCRIPTION
**Pull request by EncodePanda**
Fixes https://github.com/ArdanaLabs/danalib/issues/11

### CODE REVIEW

**Review by lukasz-golebiewski — APPROVED** [review]

**Comment by EncodePanda** [comment]
@nixinator @DarthPJB @MatthewCroughan please review :)

**Comment by MatthewCroughan** [comment]
If you want tikz as part of any usage of mkDoc you should be able to add extra build inputs as an argument, rather than making a dependency list in this function, which should remain minimal. This is okay for now, but perhaps I should just make a better function in future. It's on my to-do.

**Review by MatthewCroughan — APPROVED** [review]

**Comment by MatthewCroughan** [comment]
CI won't run against this commit, because you have forked the repo rather than pushing into it. I'm going to test it by pulling this branch in.

**Comment by MatthewCroughan** [comment]
This has allowed me to run this PR in CI.
```
git fetch origin 94de0818cf0cc1b8c07e0bb2b5ebd38480e8b20d
git push origin "94de0818cf0cc1b8c07e0bb2b5ebd38480e8b20d:refs/heads/mc/testPr11"
git push origin :refs/heads/mc/testPr11
```

**Pull request merged**
